//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Wet_Zone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Wet_Zone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings.
        /// </summary>
        public static string AboutAck {
            get {
                return ResourceManager.GetString("AboutAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an application designed by SuperNova in 2013. The goal of the project that has a main goal, &quot;Save Lives&quot;..
        /// </summary>
        public static string aboutDesc {
            get {
                return ResourceManager.GetString("aboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heading accuracy: .
        /// </summary>
        public static string accuracy {
            get {
                return ResourceManager.GetString("accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergies:.
        /// </summary>
        public static string alergies {
            get {
                return ResourceManager.GetString("alergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE WET ZONE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group:.
        /// </summary>
        public static string blood {
            get {
                return ResourceManager.GetString("blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compass on your device needs to be calibrated.
        ///  Hold the device in front of you and sweep it through a figure 8 pattern as shown
        ///  until the calibration is complete..
        /// </summary>
        public static string CompassOption {
            get {
                return ResourceManager.GetString("CompassOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1:.
        /// </summary>
        public static string contact1 {
            get {
                return ResourceManager.GetString("contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2.
        /// </summary>
        public static string contact2 {
            get {
                return ResourceManager.GetString("contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string contactHeader {
            get {
                return ResourceManager.GetString("contactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string descriptionHeader {
            get {
                return ResourceManager.GetString("descriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document:.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1:.
        /// </summary>
        public static string email1 {
            get {
                return ResourceManager.GetString("email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2:.
        /// </summary>
        public static string email2 {
            get {
                return ResourceManager.GetString("email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password:.
        /// </summary>
        public static string epassword {
            get {
                return ResourceManager.GetString("epassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general map.
        /// </summary>
        public static string generalMap {
            get {
                return ResourceManager.GetString("generalMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help!.
        /// </summary>
        public static string HelpMsg {
            get {
                return ResourceManager.GetString("HelpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icons.
        /// </summary>
        public static string icons {
            get {
                return ResourceManager.GetString("icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but this function needs to use internet..
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lantern.
        /// </summary>
        public static string lamp {
            get {
                return ResourceManager.GetString("lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        public static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled in phone settings or capabilities are not checked..
        /// </summary>
        public static string locationCheck {
            get {
                return ResourceManager.GetString("locationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string locationHeader {
            get {
                return ResourceManager.GetString("locationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string mapHeader {
            get {
                return ResourceManager.GetString("mapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Name:.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality:.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string npassword {
            get {
                return ResourceManager.GetString("npassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place.
        /// </summary>
        public static string placeHeader {
            get {
                return ResourceManager.GetString("placeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string placesHeader {
            get {
                return ResourceManager.GetString("placesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to create your profile, it&apos;s very important!.
        /// </summary>
        public static string Profile1 {
            get {
                return ResourceManager.GetString("Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic.
        /// </summary>
        public static string ProfileBasic {
            get {
                return ResourceManager.GetString("ProfileBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ProfileContacts {
            get {
                return ResourceManager.GetString("ProfileContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medicine.
        /// </summary>
        public static string ProfileMedicine {
            get {
                return ResourceManager.GetString("ProfileMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password:.
        /// </summary>
        public static string rpassword {
            get {
                return ResourceManager.GetString("rpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your safety you must create a password..
        /// </summary>
        public static string safeProfile {
            get {
                return ResourceManager.GetString("safeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SOS or Panic button is a tool designed to report to the authorities nearest your current location for assistance and likewise send a copy to our project to study the new places of danger, this place would be added to our account Twitter..
        /// </summary>
        public static string sosDescription {
            get {
                return ResourceManager.GetString("sosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been successfully created..
        /// </summary>
        public static string sucProfile {
            get {
                return ResourceManager.GetString("sucProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        public static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 1:.
        /// </summary>
        public static string telephone1 {
            get {
                return ResourceManager.GetString("telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 2:.
        /// </summary>
        public static string telephone2 {
            get {
                return ResourceManager.GetString("telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been successfully updated..
        /// </summary>
        public static string upProfile {
            get {
                return ResourceManager.GetString("upProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contacts.
        /// </summary>
        public static string viewContacts {
            get {
                return ResourceManager.GetString("viewContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Wet Zone, we recommend you download the maps that you need!.
        /// </summary>
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcomeHeader {
            get {
                return ResourceManager.GetString("welcomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        public static string wpassword {
            get {
                return ResourceManager.GetString("wpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here!.
        /// </summary>
        public static string youHere {
            get {
                return ResourceManager.GetString("youHere", resourceCulture);
            }
        }
    }
}
